### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by CaptainMat** [goenning/dotnet-outdated#2]
Hello,

I've got an error message when using: `dotnet outadated`

> No executable found matching command "dotnet-outdated"

And the nuget is correctly installed in 

> C:\Users\ME\.nuget\packages\DotNetOutdated\1.2.4

Anything else to do ?

**Comment by goenning** [comment]
Hi,

Just make sure you have this in your `project.json` 

```
  "tools": {
    "DotNetOutdated": "1.2.4"
  }
```

run `dotnet restore` and `dotnet outdated`, nothing else is needed. 

If your project.json is in a subfolder you'll have to cd to that folder.

**Comment by CaptainMat** [comment]
Right I forrgot the `cd`
